language: php

matrix:
  include:
    - php: 5.4
      env: DEPENDENCIES='low'
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
  allow_failures:
    - php: hhvm-nightly
    - env: DEPENDENCIES='low'

before_install:
  - composer self-update

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - ./bin/phpspec run --format=pretty
